fpc: fix error in build for pie
struct epoll_event was moved to epoll_event.h due to commit 64f355ffbd715a3c8b467c3b37701ad404b566b4 in platform/bionic
so we should include missing header to avoid errors in build (building with inline kernel)

hardware/sony/fingerprint/BiometricsFingerprint.cpp:339:24: error: variable has incomplete type 'struct epoll_event'
struct epoll_event evnt = {0};

Signed-off-by: David Viteri <davidteri91@gmail.com>